# Certificate for Dev Environment
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.tlsCertName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingress.tlsCertName }}  # Name of the secret where the TLS certificate will be stored
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer
  commonName: {{ .Values.grafana.ingress.hostname }}
  dnsNames:
    - {{ .Values.grafana.ingress.hostname }}