apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
    environment: "{{ .Values.environment }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  storageClassName: {{ .Values.grafana.persistence.storageClass | quote }}