apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-{{ .Values.environment }}-grafana
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.grafana.awsSecretsManager.secretName }}"
        objectType: "secretsmanager"