apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
    environment: "{{ .Values.environment }}"
spec:
  type: ClusterIP  # Internal access only; ingress will handle external traffic
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http-grafana
  selector:
    app: grafana
    environment: "{{ .Values.environment }}"