apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
    environment: "{{ .Values.environment }}"
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.grafana.serviceAccount.roleArn }}"