applicationName: proshop-backend
namespace: shop-app
serviceAccountName: proshop-sa
replicaCount: 1
image:
  repository: 975050202573.dkr.ecr.us-east-1.amazonaws.com/proshop-app/backend
port: 5000
secretProviderClassName: document-db-credentials-provider
volumename: secrets-store-inline

env:
  MONGO_URI:  "mongodb://$(DB_USERNAME):$(DB_PASSWORD)@docdb-975050202573.us-east-1.docdb-elastic.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  NODE_ENV: dev
  JWT_SECRET: supersecretkey
  PAGINATION_LIMIT: 10

service:
  name: http
  type: ClusterIP
  port: 80

ingress: 
  tlsSecretName: backend-tls-secret 
  host: proshop-app-api.akmatb.com
  ingressClass: nginx
  tll: "300"
  issuerName: letsencrypt-prod

certificate:
  tlsCertName: backend-tls-cert

awsSecrets: 
  enabled: true
  syncSecret:
    enabled: true
  awsSecretName: Admin123
  userKey: Admin123
  passKey: Admin123
  usernamePath: "Admin123"
  passwordPath: "Admin123"
  userAlias: "db-Admin123"
  passAlias: "db-Admin123" 


