apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
        - name: {{ .Values.applicationName }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: API_URL
              value: "{{ .Values.env.API_URL }}"


---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.applicationName }}-svc"
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type}}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.applicationName }}


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.applicationName }}-ingress"
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
    external-dns.alpha.kubernetes.io/ttl: "300" 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }} 
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.applicationName }}-svc"
                port:
                  number: {{ .Values.port }}



---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.tlsCertName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingress.tlsSecretName }}  
  issuerRef:
    name: letsencrypt-prod        
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host }}
  dnsNames:
    - {{ .Values.ingress.host }} 
