apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      securityContext:
        fsGroup: 65534
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              mountPath: /etc/prometheus/
            - name: {{ .Release.Name }}-pv
              mountPath: /etc/prometheus/
      volumes:
        - name: {{ .Release.Name }}-config-volume
          configMap:
            name: {{ .Release.Name }}-config
        - name: {{ .Release.Name }}-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
