apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
    environment: "{{ .Values.environment }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
  storageClassName: {{ .Values.prometheus.storageClass | quote }}