apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role-{{ .Values.environment }} 
  labels:
    app: prometheus
    environment: "{{ .Values.environment }}"
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - nodes/stats
      - services
      - endpoints
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - configmaps
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
      - daemonsets
    verbs:
      - get
      - list
      - watch

---
# Cluster Role Binding for Prometheus
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-clusterrolebinding-{{ .Values.environment }}
  labels:
    app: prometheus
    environment: "{{ .Values.environment }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-cluster-role-{{ .Values.environment }} 
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ .Values.namespace }}

---
# Cluster Role Binding for kube-state-metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics-binding-{{ .Values.environment }}
  labels:
    app: kube-state-metrics
    role: cluster-role-binding
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-cluster-role-{{ .Values.environment }} 
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics-sa
    namespace: kube-system