# Prometheus Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
    environment: "{{ .Values.environment }}"

---  
# Kube-state-metrics Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics-sa
  namespace: kube-system
  labels:
    app: kube-state-metrics

---  
# Node exporter Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-node-exporter-sa
  namespace: {{ .Values.namespace }}
  labels: 
    app: node-exporter