# Prometheus service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.Namespace }}
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: prometheus

---    
# Kube-state-metrics Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubeStateMetrics.serviceName }}-{{ .Values.environment }}
  namespace: kube-system
  labels: 
    app: kube-state-metrics
spec:
  type: ClusterIP       
  ports:
  - name: http-metrics
    port: 8080           # Default port for kube-state-metrics
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry   
  selector:
    k8s-app: kube-state-metrics  

---  
# Node exporter Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-exporter
  namespace: {{ .Values.Namespace }}
  labels:
    app: node-exporter
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  selector:
    app: node-exporter
  type: ClusterIP