name: Application CI/CD

on:
   # trigger/start job when push happens to main or staging or feature/** branch
  push:
    branches: [ "main", "staging", "feature/**" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

# workflow level variable, available only within this YAML file to this workflow
env:
  ENVIRONMENT_STAGE: "dev"

jobs:
  app-deploy:
    # if main branch => production environment
    # if staging branch => staging environment
    # if any other branch name => dev environment
    environment: "dev"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: ${{ vars.IAM_ROLE }}
        aws-region: us-east-1

# CI
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      if: ${{ env.ENVIRONMENT_STAGE != 'dev' }}


    - name: Build and Push Backend image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: proshop-backend
        IMAGE_TAG: ${{ github.sha }}
      working-directory: ./backend
      run: |
        docker build -t $REPOSITORY:$IMAGE_TAG .
        docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Build and Push Frontend image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: proshop-frontend
        IMAGE_TAG: ${{ github.sha }}
      working-directory: ./frontend
      run: |
        docker build -t $REPOSITORY:$IMAGE_TAG .
        docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

# CD 
    - name: Login to EKS
      run: aws eks update-kubeconfig --name temporary-eks-cluster-${{ env.ENVIRONMENT_STAGE }}
    


    - name: Deploy the Frontend App
      env:
        SEMANTIC_TAG: "v1.0.1" # Manually set
      run: |
        if [ "${{ env.ENVIRONMENT_STAGE }}" = "dev" ]; then
          IMAGE_TAG=${{ github.sha }}
        else
          IMAGE_TAG=${{ env.SEMANTIC_TAG }}
        fi

        helm upgrade --install frontend \
         ./proshop-app/app-helm-chart/ --values ./proshop-app/app-helm-chart/frontend-chart/values.yml \
         --set appConfig.env.NODE_ENV=dev \
         --set image.tag=$IMAGE_TAG \
         --namespace shop-app --create-namespace

    - name: Deploy the Backend App
      env:
        SEMANTIC_TAG: "v1.0.1"  # Manually set
      run: |
        if [ "${{ env.ENVIRONMENT_STAGE }}" = "dev" ]; then
          IMAGE_TAG=${{ github.sha }}
        else
          IMAGE_TAG=${{ env.SEMANTIC_TAG }}
        fi

        helm upgrade --install backend \
         ./proshop-app/app-helm-chart/ --values ./proshop-app/app-helm-chart/backend-chart/values.yaml \
         --set image.tag=$IMAGE_TAG \
         --namespace shop-app --create-namespace 